package shop.convertio.model;

public class FileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.upload_time
     *
     * @mbggenerated
     */
    private Long uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.convert_start_time
     *
     * @mbggenerated
     */
    private Long convertStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.convert_stop_time
     *
     * @mbggenerated
     */
    private Long convertStopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.download_time
     *
     * @mbggenerated
     */
    private Long downloadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.src_real_name
     *
     * @mbggenerated
     */
    private String srcRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.src_ext_name
     *
     * @mbggenerated
     */
    private String srcExtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.src_file_name
     *
     * @mbggenerated
     */
    private String srcFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.target_ext_name
     *
     * @mbggenerated
     */
    private String targetExtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.target_path
     *
     * @mbggenerated
     */
    private String targetPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.id
     *
     * @return the value of file_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.id
     *
     * @param id the value for file_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.upload_time
     *
     * @return the value of file_info.upload_time
     *
     * @mbggenerated
     */
    public Long getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.upload_time
     *
     * @param uploadTime the value for file_info.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Long uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.convert_start_time
     *
     * @return the value of file_info.convert_start_time
     *
     * @mbggenerated
     */
    public Long getConvertStartTime() {
        return convertStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.convert_start_time
     *
     * @param convertStartTime the value for file_info.convert_start_time
     *
     * @mbggenerated
     */
    public void setConvertStartTime(Long convertStartTime) {
        this.convertStartTime = convertStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.convert_stop_time
     *
     * @return the value of file_info.convert_stop_time
     *
     * @mbggenerated
     */
    public Long getConvertStopTime() {
        return convertStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.convert_stop_time
     *
     * @param convertStopTime the value for file_info.convert_stop_time
     *
     * @mbggenerated
     */
    public void setConvertStopTime(Long convertStopTime) {
        this.convertStopTime = convertStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.download_time
     *
     * @return the value of file_info.download_time
     *
     * @mbggenerated
     */
    public Long getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.download_time
     *
     * @param downloadTime the value for file_info.download_time
     *
     * @mbggenerated
     */
    public void setDownloadTime(Long downloadTime) {
        this.downloadTime = downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.src_real_name
     *
     * @return the value of file_info.src_real_name
     *
     * @mbggenerated
     */
    public String getSrcRealName() {
        return srcRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.src_real_name
     *
     * @param srcRealName the value for file_info.src_real_name
     *
     * @mbggenerated
     */
    public void setSrcRealName(String srcRealName) {
        this.srcRealName = srcRealName == null ? null : srcRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.src_ext_name
     *
     * @return the value of file_info.src_ext_name
     *
     * @mbggenerated
     */
    public String getSrcExtName() {
        return srcExtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.src_ext_name
     *
     * @param srcExtName the value for file_info.src_ext_name
     *
     * @mbggenerated
     */
    public void setSrcExtName(String srcExtName) {
        this.srcExtName = srcExtName == null ? null : srcExtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.src_file_name
     *
     * @return the value of file_info.src_file_name
     *
     * @mbggenerated
     */
    public String getSrcFileName() {
        return srcFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.src_file_name
     *
     * @param srcFileName the value for file_info.src_file_name
     *
     * @mbggenerated
     */
    public void setSrcFileName(String srcFileName) {
        this.srcFileName = srcFileName == null ? null : srcFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.target_ext_name
     *
     * @return the value of file_info.target_ext_name
     *
     * @mbggenerated
     */
    public String getTargetExtName() {
        return targetExtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.target_ext_name
     *
     * @param targetExtName the value for file_info.target_ext_name
     *
     * @mbggenerated
     */
    public void setTargetExtName(String targetExtName) {
        this.targetExtName = targetExtName == null ? null : targetExtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.target_path
     *
     * @return the value of file_info.target_path
     *
     * @mbggenerated
     */
    public String getTargetPath() {
        return targetPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.target_path
     *
     * @param targetPath the value for file_info.target_path
     *
     * @mbggenerated
     */
    public void setTargetPath(String targetPath) {
        this.targetPath = targetPath == null ? null : targetPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.key
     *
     * @return the value of file_info.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.key
     *
     * @param key the value for file_info.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }
}